package com.pma.smsecure.Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CACHE.
 */
public class Cache {

    private Long id;
    private String sms_parts;
    private String phoneNumber;

    public Cache() {
    }

    public Cache(Long id) {
        this.id = id;
    }

    public Cache(Long id, String sms_parts, String phoneNumber) {
        this.id = id;
        this.sms_parts = sms_parts;
        this.phoneNumber = phoneNumber;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSms_parts() {
        return sms_parts;
    }

    public void setSms_parts(String sms_parts) {
        this.sms_parts = sms_parts;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

}
