package com.pma.smsecure.Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONTACT.
 */
public class Contact {

    private Long id;
    private Integer phone_id_contact;
    private String publicKey;
    private String phoneNumber;

    public Contact() {
    }

    public Contact(Long id) {
        this.id = id;
    }

    public Contact(Long id, Integer phone_id_contact, String publicKey, String phoneNumber) {
        this.id = id;
        this.phone_id_contact = phone_id_contact;
        this.publicKey = publicKey;
        this.phoneNumber = phoneNumber;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getPhone_id_contact() {
        return phone_id_contact;
    }

    public void setPhone_id_contact(Integer phone_id_contact) {
        this.phone_id_contact = phone_id_contact;
    }

    public String getPublicKey() {
        return publicKey;
    }

    public void setPublicKey(String publicKey) {
        this.publicKey = publicKey;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

}
