package com.pma.smsecure.Dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.pma.smsecure.Dao.Cache;
import com.pma.smsecure.Dao.Contact;
import com.pma.smsecure.Dao.Conversation;
import com.pma.smsecure.Dao.SMS;
import com.pma.smsecure.Dao.User;

import com.pma.smsecure.Dao.CacheDao;
import com.pma.smsecure.Dao.ContactDao;
import com.pma.smsecure.Dao.ConversationDao;
import com.pma.smsecure.Dao.SMSDao;
import com.pma.smsecure.Dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cacheDaoConfig;
    private final DaoConfig contactDaoConfig;
    private final DaoConfig conversationDaoConfig;
    private final DaoConfig sMSDaoConfig;
    private final DaoConfig userDaoConfig;

    private final CacheDao cacheDao;
    private final ContactDao contactDao;
    private final ConversationDao conversationDao;
    private final SMSDao sMSDao;
    private final UserDao userDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cacheDaoConfig = daoConfigMap.get(CacheDao.class).clone();
        cacheDaoConfig.initIdentityScope(type);

        contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
        contactDaoConfig.initIdentityScope(type);

        conversationDaoConfig = daoConfigMap.get(ConversationDao.class).clone();
        conversationDaoConfig.initIdentityScope(type);

        sMSDaoConfig = daoConfigMap.get(SMSDao.class).clone();
        sMSDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        cacheDao = new CacheDao(cacheDaoConfig, this);
        contactDao = new ContactDao(contactDaoConfig, this);
        conversationDao = new ConversationDao(conversationDaoConfig, this);
        sMSDao = new SMSDao(sMSDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Cache.class, cacheDao);
        registerDao(Contact.class, contactDao);
        registerDao(Conversation.class, conversationDao);
        registerDao(SMS.class, sMSDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        cacheDaoConfig.getIdentityScope().clear();
        contactDaoConfig.getIdentityScope().clear();
        conversationDaoConfig.getIdentityScope().clear();
        sMSDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
    }

    public CacheDao getCacheDao() {
        return cacheDao;
    }

    public ContactDao getContactDao() {
        return contactDao;
    }

    public ConversationDao getConversationDao() {
        return conversationDao;
    }

    public SMSDao getSMSDao() {
        return sMSDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
